$terminal = ghostty
$file_explorer = $terminal -e yazi
$browser = zen-browser
$menu = wofi --show drun -i
$discord = vesktop
$notes = obsidian --enable-features=UseOzonePlatform --ozone-platform=wayland
$notification_center = swaync-client -t
$video_player = mpv
$unicode_picker = # make a wofi/rofi menu for a unicode picker
$restart_modules = killall waybar; waybar; killall swaync; swaync &

# Script paths
$clipboard_menu = ~/.scripts/wofi-clipboard-selector.sh
$zen_mode_toggle = ~/.scripts/zen_mode_toggle.sh
$scrcpy_menu = ~/.scripts/scrcpy-menu.sh
$pass_menu = ~/.scripts/wofi-passmenu.sh
$logout_menu = ~/.scripts/wlogout-toggle.sh 
$battery_watcher = ~/.scripts/battery_watcher.sh
