# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Example windowrule v1
# windowrule = float, ^(kitty)$

windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur on, match:class ^(xwaylandvideobridge)$
windowrule = no_focus on, match:class ^(xwaylandvideobridge)$
#
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize,

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1,match:fullscreen 0, match:pin 0

windowrule = border_color rgb(ffffff)/rgb(ffffff), match:float 1
windowrule = idle_inhibit focus, match:class firefox
windowrule = idle_inhibit focus, match:class zen
windowrule = fullscreen_state 0 3, match:class zen
windowrule = opacity 0.95, match:class deezer-desktop
windowrule = opacity 0.98, match:initial_title ^(.*Discord.*)$
windowrule = fullscreen_state 0 2, match:initial_title ^(.*Discord.*)$
windowrule = workspace 9, match:initial_title ^(.*Discord.*)$
windowrule = workspace 9, match:class com.obsproject.Studio
windowrule = workspace 10, match:initial_title ^(.*Projector.*)$
windowrule = opacity 0.95, match:class com.github.th_ch.youtube_music
windowrule = workspace 10, match:class com.github.th_ch.youtube_music

## Picture in Picture 
windowrule = float on, match:initial_title (Picture-in-Picture)
windowrule = size 585 330, match:initial_title (Picture-in-Picture)
windowrule = move (monitor_w-585-15) 15, match:initial_title (Picture-in-Picture)
windowrule = pin on, match:initial_title (Picture-in-Picture)
windowrule = no_dim on, match:initial_title (Picture-in-Picture)
windowrule = opacity 1 0.8, match:initial_title (Picture-in-Picture)
windowrule = no_initial_focus on, match:initial_title (Picture-in-Picture)
windowrule = opacity 1, match:initial_title (Picture-in-Picture), match:float 0

windowrule = float on, match:initial_title (Ghostty), match:workspace name:special:scratchpad
windowrule = size 1058 696, match:initial_title (Ghostty), match:workspace name:special:scratchpad
windowrule = center on, match:initial_title (Ghostty), match:workspace name:special:scratchpad
# LAYER RULES
layerrule = blur on, match:initial_title swaync-control-center
